### ISSUE TITLE
Inserir no projeto a opção getPaymentMethod

### ISSUE THREAD

**Issue by marciotisouza** [WashingtonInoveApps/mercadopago_transparent#4]
Excelente trabalho !!!

    Já uso o checkout transparente através do javascript com mercadopago.js, nela temos a opção getPaymentMethod que passando os 6 primeiros dígitos do número do cartão, retorna o id do tipo de pagamento e mais informações referente ao cartão para personalizar a tela do usuário. Se for possível incluir está opção neste pacote ficaria perfeito !

**Comment by marcobraghim** [comment]
Para obter o issuer id. No parametro `bins` informar 6 primeiros dígitos do cartão
```curl
curl --location --request GET 'https://api.mercadopago.com/v1/payment_methods/search?bins=423564&public_key=SUA_PUBLIC_KEY'
```

Para obter parcelas com base no valor. No parametro `bin` informar 8 primeiros dígitos do cartão
```curl
curl --location --request GET 'https://api.mercadopago.com/v1/payment_methods/installments?locale=pt-BR&bin=50314332&amount=50&public_key=SUA_PUBLIC_KEY'
```

**Comment by marcobraghim** [comment]
Estes dois métodos foram adicionados no seguinte PR
[Pull Request](https://github.com/WashingtonInoveApps/mercadopago_transparent/pull/6)

**Comment by WashingtonInoveApps** [comment]
ready !!
